[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "riot-tap"
dependencies = [
    "singer-sdk",
    "requests",
    "python-dateutil",
    "meltano",
    "backoff"
]